[tool.poetry]
name = "latent-diffusion"
version = "0.1.0"
description = ""
authors = ["technillogue <technillogue@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
cudatoolkit = "11.0"
pytorch = "1.7.0"

torchvision= "0.8.1"
numpy="1.19.2"
albumentations = "0.4.3"
opencv-python = "4.1.2.30"
pudb = "2019.2"
imageio = "2.9.0"
imageio-ffmpeg = "0.4.2"
pytorch-lightning = "1.4.2"
omegaconf = "2.1.1"
#test-tube= ">0.7.5"
#streamlit= ">0.73.1"
einops = "0.3.0"
torch-fidelity = "0.3.0"
transformers = "4.3.1"
taming-transformers = {git="https://github.com/CompVis/taming-transformers", rev="master"}
CLIP = {git="https://github.com/openai/CLIP", rev="main"}
test-tube = "^0.7.5"
streamlit = "^1.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
